CARLA_CONFIG:
  NUM_OF_VEHICLES: 10
  NUM_OF_WALKERS: 5

AGENT_CONFIG:
  TRANSFORM: { location: [ 124, 226, 0.65 ], rotation: [ 0, 0, 0 ] }
  BLUEPRINT: vehicle.tesla.model3

SENSOR_CONFIG:
  RGB:
    TRANSFORM: { location: [ 10, 0, 4 ], rotation: [ -20, -90, 0 ]}
    BLUEPRINT: sensor.camera.rgb
    ATTRIBUTE: { image_size_x: 720, image_size_y: 360, fov: 90 }

  DEPTH_RGB:
    TRANSFORM: { location: [ 10, 0, 4 ], rotation: [ -20, -90, 0 ]}
    BLUEPRINT: sensor.camera.depth
    ATTRIBUTE: { image_size_x: 720, image_size_y: 360, fov: 90 }

  LIDAR:
    TRANSFORM: { location: [ 10, 0, 4 ], rotation: [ -20, -90, 0 ]}
    BLUEPRINT: sensor.lidar.ray_cast
    ATTRIBUTE: { range: 70, rotation_frequency: 20, upper_fov: 40, lower_fov: -30, points_per_second: 1280000, channels: 64 }

  SEMANTIC_LIDAR:
    TRANSFORM: { location: [ 10, 0, 4 ], rotation: [ -20, -90, 0 ]}
    BLUEPRINT: sensor.lidar.ray_cast_semantic
    ATTRIBUTE: { range: 70, rotation_frequency: 20, upper_fov: 40, lower_fov: -30, points_per_second: 1280000, channels: 64 }

FILTER_CONFIG:
  PRELIMINARY_FILTER_DISTANCE: 50
  MAX_RENDER_DEPTH_IN_METERS: 50
  MIN_VISIBLE_VERTICES_FOR_RENDER: 3
  MAX_OUT_VERTICES_FOR_RENDER: 5

SAVE_CONFIG:
  ROOT_PATH: data/test
  STEP: 20